services:

  node1:
    image: hazelcast/hazelcast
    container_name: node1
    networks:
      - hazelcast_network
    ports:
      - 5701:5701

  node2:
    image: hazelcast/hazelcast
    container_name: node2
    networks:
      - hazelcast_network
    ports:
      - 5702:5701

networks:
  hazelcast_network:
    driver: bridge